# Generated by Django 5.2.2 on 2025-06-12 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_skills'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Skills',
            new_name='Skill',
        ),
    ]
