# Generated by Django 5.2.2 on 2025-06-20 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_rename_skills_skill'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('icon', models.CharField(choices=[('bi bi-camera', 'Camera'), ('bi bi-heart-fill', 'Heart'), ('bi bi-calendar-event', 'Calendar'), ('bi bi-geo-alt', 'location'), ('bi bi-person-circle', 'person'), ('bi bi-sliders', 'sliders'), ('bi bi-camera-reels-fill', 'camera reels'), ('bi bi-camera-video', 'drone'), ('bi bi-box-seam', 'box')], max_length=100)),
            ],
        ),
    ]
